spring:
  application.name: session
  datasource:
    url: jdbc:mariadb://localhost:3306/common
    username: common
    password: pass
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    properties:
      hibernate:
        "[enable_lazy_load_no_trans]": true
  data:
    redis:
      host: localhost
      port: 6379
